CREATE PROC REPORTE_CINE
@idcine int
AS
BEGIN
	SELECT CINE.Id AS IdCine, CINE.Nombre AS NombreCine, COUNT(ENTRADA.Id) AS CantidadEntradasVendidas
	FROM CINE
	INNER JOIN CINE_SALA ON CINE.Id = CINE_SALA.IdCine
	INNER JOIN SALA ON CINE_SALA.IdSala = SALA.Id
	INNER JOIN SALA_FUNCION ON SALA.Id = SALA_FUNCION.IdSala
	INNER JOIN FUNCION ON SALA_FUNCION.IdFuncion = FUNCION.Id
	INNER JOIN ENTRADA ON FUNCION.Id = ENTRADA.IdFuncion
	WHERE CINE.Id = @idcine
	AND ENTRADA.Estado = 'Pagada'
	GROUP BY CINE.Id, CINE.Nombre;
END
GO