CREATE PROC BITACORAEVENTOS_INSERTAR
@idusuario int, @fecha datetime, @accion varchar(50)
AS
BEGIN
	INSERT INTO BITACORAEVENTOS VALUES (@idusuario, @fecha, @accion)
END
GO

CREATE PROC BITACORAEVENTOS_LISTAR
AS
BEGIN
	SELECT * FROM BITACORAEVENTOS
END
GO
